//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica4.WSBanguat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class InfoVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Practica4.WSBanguat.Variable[] VariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Practica4.WSBanguat.Var[] CambioDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Practica4.WSBanguat.VarDolar[] CambioDolarField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Practica4.WSBanguat.Variable[] Variables {
            get {
                return this.VariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariablesField, value) != true)) {
                    this.VariablesField = value;
                    this.RaisePropertyChanged("Variables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Practica4.WSBanguat.Var[] CambioDia {
            get {
                return this.CambioDiaField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDiaField, value) != true)) {
                    this.CambioDiaField = value;
                    this.RaisePropertyChanged("CambioDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Practica4.WSBanguat.VarDolar[] CambioDolar {
            get {
                return this.CambioDolarField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDolarField, value) != true)) {
                    this.CambioDolarField = value;
                    this.RaisePropertyChanged("CambioDolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Variable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Var : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta {
            get {
                return this.ventaField;
            }
            set {
                if ((this.ventaField.Equals(value) != true)) {
                    this.ventaField = value;
                    this.RaisePropertyChanged("venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra {
            get {
                return this.compraField;
            }
            set {
                if ((this.compraField.Equals(value) != true)) {
                    this.compraField = value;
                    this.RaisePropertyChanged("compra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class VarDolar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float referenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia {
            get {
                return this.referenciaField;
            }
            set {
                if ((this.referenciaField.Equals(value) != true)) {
                    this.referenciaField = value;
                    this.RaisePropertyChanged("referencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class DataVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Practica4.WSBanguat.Var[] VarsField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Practica4.WSBanguat.Var[] Vars {
            get {
                return this.VarsField;
            }
            set {
                if ((object.ReferenceEquals(this.VarsField, value) != true)) {
                    this.VarsField = value;
                    this.RaisePropertyChanged("Vars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="WSBanguat.TipoCambioSoap")]
    public interface TipoCambioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesDisponiblesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        Practica4.WSBanguat.VariablesDisponiblesResponse VariablesDisponibles(Practica4.WSBanguat.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<Practica4.WSBanguat.VariablesDisponiblesResponse> VariablesDisponiblesAsync(Practica4.WSBanguat.VariablesDisponiblesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        Practica4.WSBanguat.VariablesResponse Variables(Practica4.WSBanguat.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<Practica4.WSBanguat.VariablesResponse> VariablesAsync(Practica4.WSBanguat.VariablesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        Practica4.WSBanguat.TipoCambioFechaInicialResponse TipoCambioFechaInicial(Practica4.WSBanguat.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(Practica4.WSBanguat.TipoCambioFechaInicialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        Practica4.WSBanguat.TipoCambioRangoResponse TipoCambioRango(Practica4.WSBanguat.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioRangoResponse> TipoCambioRangoAsync(Practica4.WSBanguat.TipoCambioRangoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        Practica4.WSBanguat.TipoCambioFechaInicialMonedaResponse TipoCambioFechaInicialMoneda(Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        Practica4.WSBanguat.TipoCambioRangoMonedaResponse TipoCambioRangoMoneda(Practica4.WSBanguat.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(Practica4.WSBanguat.TipoCambioRangoMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        Practica4.WSBanguat.TipoCambioDiaResponse TipoCambioDia(Practica4.WSBanguat.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioDiaResponse> TipoCambioDiaAsync(Practica4.WSBanguat.TipoCambioDiaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaStringResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        Practica4.WSBanguat.TipoCambioDiaStringResponse TipoCambioDiaString(Practica4.WSBanguat.TipoCambioDiaStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(Practica4.WSBanguat.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest() {
        }
        
        public VariablesDisponiblesRequest(Practica4.WSBanguat.VariablesDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody {
        
        public VariablesDisponiblesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse() {
        }
        
        public VariablesDisponiblesResponse(Practica4.WSBanguat.VariablesDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Practica4.WSBanguat.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody() {
        }
        
        public VariablesDisponiblesResponseBody(Practica4.WSBanguat.InfoVariable VariablesDisponiblesResult) {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.VariablesRequestBody Body;
        
        public VariablesRequest() {
        }
        
        public VariablesRequest(Practica4.WSBanguat.VariablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody() {
        }
        
        public VariablesRequestBody(int variable) {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.VariablesResponseBody Body;
        
        public VariablesResponse() {
        }
        
        public VariablesResponse(Practica4.WSBanguat.VariablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Practica4.WSBanguat.InfoVariable VariablesResult;
        
        public VariablesResponseBody() {
        }
        
        public VariablesResponseBody(Practica4.WSBanguat.InfoVariable VariablesResult) {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest() {
        }
        
        public TipoCambioFechaInicialRequest(Practica4.WSBanguat.TipoCambioFechaInicialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody() {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit) {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse() {
        }
        
        public TipoCambioFechaInicialResponse(Practica4.WSBanguat.TipoCambioFechaInicialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Practica4.WSBanguat.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody() {
        }
        
        public TipoCambioFechaInicialResponseBody(Practica4.WSBanguat.DataVariable TipoCambioFechaInicialResult) {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest() {
        }
        
        public TipoCambioRangoRequest(Practica4.WSBanguat.TipoCambioRangoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody() {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse() {
        }
        
        public TipoCambioRangoResponse(Practica4.WSBanguat.TipoCambioRangoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Practica4.WSBanguat.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody() {
        }
        
        public TipoCambioRangoResponseBody(Practica4.WSBanguat.DataVariable TipoCambioRangoResult) {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest() {
        }
        
        public TipoCambioFechaInicialMonedaRequest(Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody() {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda) {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse() {
        }
        
        public TipoCambioFechaInicialMonedaResponse(Practica4.WSBanguat.TipoCambioFechaInicialMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Practica4.WSBanguat.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody() {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(Practica4.WSBanguat.DataVariable TipoCambioFechaInicialMonedaResult) {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest() {
        }
        
        public TipoCambioRangoMonedaRequest(Practica4.WSBanguat.TipoCambioRangoMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody() {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse() {
        }
        
        public TipoCambioRangoMonedaResponse(Practica4.WSBanguat.TipoCambioRangoMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Practica4.WSBanguat.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody() {
        }
        
        public TipoCambioRangoMonedaResponseBody(Practica4.WSBanguat.DataVariable TipoCambioRangoMonedaResult) {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest() {
        }
        
        public TipoCambioDiaRequest(Practica4.WSBanguat.TipoCambioDiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody {
        
        public TipoCambioDiaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse() {
        }
        
        public TipoCambioDiaResponse(Practica4.WSBanguat.TipoCambioDiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Practica4.WSBanguat.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody() {
        }
        
        public TipoCambioDiaResponseBody(Practica4.WSBanguat.InfoVariable TipoCambioDiaResult) {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest() {
        }
        
        public TipoCambioDiaStringRequest(Practica4.WSBanguat.TipoCambioDiaStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody {
        
        public TipoCambioDiaStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public Practica4.WSBanguat.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse() {
        }
        
        public TipoCambioDiaStringResponse(Practica4.WSBanguat.TipoCambioDiaStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody() {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult) {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoCambioSoapChannel : Practica4.WSBanguat.TipoCambioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<Practica4.WSBanguat.TipoCambioSoap>, Practica4.WSBanguat.TipoCambioSoap {
        
        public TipoCambioSoapClient() {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica4.WSBanguat.VariablesDisponiblesResponse Practica4.WSBanguat.TipoCambioSoap.VariablesDisponibles(Practica4.WSBanguat.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponibles(request);
        }
        
        public Practica4.WSBanguat.InfoVariable VariablesDisponibles() {
            Practica4.WSBanguat.VariablesDisponiblesRequest inValue = new Practica4.WSBanguat.VariablesDisponiblesRequest();
            inValue.Body = new Practica4.WSBanguat.VariablesDisponiblesRequestBody();
            Practica4.WSBanguat.VariablesDisponiblesResponse retVal = ((Practica4.WSBanguat.TipoCambioSoap)(this)).VariablesDisponibles(inValue);
            return retVal.Body.VariablesDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica4.WSBanguat.VariablesDisponiblesResponse> Practica4.WSBanguat.TipoCambioSoap.VariablesDisponiblesAsync(Practica4.WSBanguat.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica4.WSBanguat.VariablesDisponiblesResponse> VariablesDisponiblesAsync() {
            Practica4.WSBanguat.VariablesDisponiblesRequest inValue = new Practica4.WSBanguat.VariablesDisponiblesRequest();
            inValue.Body = new Practica4.WSBanguat.VariablesDisponiblesRequestBody();
            return ((Practica4.WSBanguat.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica4.WSBanguat.VariablesResponse Practica4.WSBanguat.TipoCambioSoap.Variables(Practica4.WSBanguat.VariablesRequest request) {
            return base.Channel.Variables(request);
        }
        
        public Practica4.WSBanguat.InfoVariable Variables(int variable) {
            Practica4.WSBanguat.VariablesRequest inValue = new Practica4.WSBanguat.VariablesRequest();
            inValue.Body = new Practica4.WSBanguat.VariablesRequestBody();
            inValue.Body.variable = variable;
            Practica4.WSBanguat.VariablesResponse retVal = ((Practica4.WSBanguat.TipoCambioSoap)(this)).Variables(inValue);
            return retVal.Body.VariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica4.WSBanguat.VariablesResponse> Practica4.WSBanguat.TipoCambioSoap.VariablesAsync(Practica4.WSBanguat.VariablesRequest request) {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica4.WSBanguat.VariablesResponse> VariablesAsync(int variable) {
            Practica4.WSBanguat.VariablesRequest inValue = new Practica4.WSBanguat.VariablesRequest();
            inValue.Body = new Practica4.WSBanguat.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((Practica4.WSBanguat.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica4.WSBanguat.TipoCambioFechaInicialResponse Practica4.WSBanguat.TipoCambioSoap.TipoCambioFechaInicial(Practica4.WSBanguat.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicial(request);
        }
        
        public Practica4.WSBanguat.DataVariable TipoCambioFechaInicial(string fechainit) {
            Practica4.WSBanguat.TipoCambioFechaInicialRequest inValue = new Practica4.WSBanguat.TipoCambioFechaInicialRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            Practica4.WSBanguat.TipoCambioFechaInicialResponse retVal = ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioFechaInicial(inValue);
            return retVal.Body.TipoCambioFechaInicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioFechaInicialResponse> Practica4.WSBanguat.TipoCambioSoap.TipoCambioFechaInicialAsync(Practica4.WSBanguat.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit) {
            Practica4.WSBanguat.TipoCambioFechaInicialRequest inValue = new Practica4.WSBanguat.TipoCambioFechaInicialRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica4.WSBanguat.TipoCambioRangoResponse Practica4.WSBanguat.TipoCambioSoap.TipoCambioRango(Practica4.WSBanguat.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRango(request);
        }
        
        public Practica4.WSBanguat.DataVariable TipoCambioRango(string fechainit, string fechafin) {
            Practica4.WSBanguat.TipoCambioRangoRequest inValue = new Practica4.WSBanguat.TipoCambioRangoRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            Practica4.WSBanguat.TipoCambioRangoResponse retVal = ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioRango(inValue);
            return retVal.Body.TipoCambioRangoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioRangoResponse> Practica4.WSBanguat.TipoCambioSoap.TipoCambioRangoAsync(Practica4.WSBanguat.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin) {
            Practica4.WSBanguat.TipoCambioRangoRequest inValue = new Practica4.WSBanguat.TipoCambioRangoRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica4.WSBanguat.TipoCambioFechaInicialMonedaResponse Practica4.WSBanguat.TipoCambioSoap.TipoCambioFechaInicialMoneda(Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMoneda(request);
        }
        
        public Practica4.WSBanguat.DataVariable TipoCambioFechaInicialMoneda(string fechainit, int moneda) {
            Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequest inValue = new Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            Practica4.WSBanguat.TipoCambioFechaInicialMonedaResponse retVal = ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioFechaInicialMoneda(inValue);
            return retVal.Body.TipoCambioFechaInicialMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioFechaInicialMonedaResponse> Practica4.WSBanguat.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda) {
            Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequest inValue = new Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica4.WSBanguat.TipoCambioRangoMonedaResponse Practica4.WSBanguat.TipoCambioSoap.TipoCambioRangoMoneda(Practica4.WSBanguat.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMoneda(request);
        }
        
        public Practica4.WSBanguat.DataVariable TipoCambioRangoMoneda(string fechainit, string fechafin, int moneda) {
            Practica4.WSBanguat.TipoCambioRangoMonedaRequest inValue = new Practica4.WSBanguat.TipoCambioRangoMonedaRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            Practica4.WSBanguat.TipoCambioRangoMonedaResponse retVal = ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioRangoMoneda(inValue);
            return retVal.Body.TipoCambioRangoMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioRangoMonedaResponse> Practica4.WSBanguat.TipoCambioSoap.TipoCambioRangoMonedaAsync(Practica4.WSBanguat.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda) {
            Practica4.WSBanguat.TipoCambioRangoMonedaRequest inValue = new Practica4.WSBanguat.TipoCambioRangoMonedaRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica4.WSBanguat.TipoCambioDiaResponse Practica4.WSBanguat.TipoCambioSoap.TipoCambioDia(Practica4.WSBanguat.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDia(request);
        }
        
        public Practica4.WSBanguat.InfoVariable TipoCambioDia() {
            Practica4.WSBanguat.TipoCambioDiaRequest inValue = new Practica4.WSBanguat.TipoCambioDiaRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioDiaRequestBody();
            Practica4.WSBanguat.TipoCambioDiaResponse retVal = ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioDia(inValue);
            return retVal.Body.TipoCambioDiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioDiaResponse> Practica4.WSBanguat.TipoCambioSoap.TipoCambioDiaAsync(Practica4.WSBanguat.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioDiaResponse> TipoCambioDiaAsync() {
            Practica4.WSBanguat.TipoCambioDiaRequest inValue = new Practica4.WSBanguat.TipoCambioDiaRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioDiaRequestBody();
            return ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Practica4.WSBanguat.TipoCambioDiaStringResponse Practica4.WSBanguat.TipoCambioSoap.TipoCambioDiaString(Practica4.WSBanguat.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaString(request);
        }
        
        public string TipoCambioDiaString() {
            Practica4.WSBanguat.TipoCambioDiaStringRequest inValue = new Practica4.WSBanguat.TipoCambioDiaStringRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioDiaStringRequestBody();
            Practica4.WSBanguat.TipoCambioDiaStringResponse retVal = ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioDiaString(inValue);
            return retVal.Body.TipoCambioDiaStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioDiaStringResponse> Practica4.WSBanguat.TipoCambioSoap.TipoCambioDiaStringAsync(Practica4.WSBanguat.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<Practica4.WSBanguat.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync() {
            Practica4.WSBanguat.TipoCambioDiaStringRequest inValue = new Practica4.WSBanguat.TipoCambioDiaStringRequest();
            inValue.Body = new Practica4.WSBanguat.TipoCambioDiaStringRequestBody();
            return ((Practica4.WSBanguat.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
    }
}
